name: Publish to PyPI

on:
  push:
    branches:
      - ci_build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            archs: auto
          - os: macos-14
            archs: arm64
          - os: macos-13
            archs: x86_64
          - os: macos-13
            archs: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update &&
          sudo apt-get install -y libgeos++-dev         

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Setup MacOS
        if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
        run: |
          echo "CC=gcc-14" >> "$GITHUB_ENV"
          echo "CXX=g++-14" >> "$GITHUB_ENV"
          if [[ ${{ matrix.os }} == 'macos-14' ]]; then
            CIBW="MACOSX_DEPLOYMENT_TARGET=14"
            echo "CIBW_ENVIRONMENT_MACOS=$CIBW" >> "$GITHUB_ENV"
          else
            CIBW="MACOSX_DEPLOYMENT_TARGET=10.12"
            echo "CIBW_ENVIRONMENT_MACOS=$CIBW" >> "$GITHUB_ENV"
          fi
            

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: pp* cp36* cp37* *-win32 *-manylinux_i686 *-musllinux_*
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_TEST_COMMAND_MACOS: python -c "import seislib"
          
      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl